# ServiceAccount for External Secrets to authenticate with AWS
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: grocery-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::700213287888:role/GroceryAppSecretsRole
